name: 'dbt_course_practice'
version: '1.0.0'

# Укажите, какой профиль конфигурации использовать.
profile: 'dbt_course_practice'

# Пути к различным типам файлов проекта.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # Директории для удаления через `dbt clean`
  - "target"
  - "dbt_packages"

# Настройки моделей
models:
# +post_hook: "{{ check_dependencies() }}"
  dbt_course_practice:
    staging:
      +tags: ['staging']
      flights:
        +materialized: table  # Указываем материализацию как "таблица"
    intermediate:
      +tags: ['intermediate']
      flights:
        +materialized: table  # Указываем материализацию как "таблица"
    marts:
      flights:
        +materialized: table  # Указываем материализацию как "таблица"

seeds:
  dbt_course_practice:
    schema: seeds

